# src/main/resources/application.yml

spring:
  profiles:
    group:
      local: "common, local"
      dev: "common, dev"
      prod: "common, prod"
    active: local

---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: toss-plcc
