### Login and Redirect
POST http://localhost:8080/api/login-and-redirect
Content-Type: application/json

{
  "grantType": "authorization_code",
  "clientId": "my-client-id",
  "redirectUrl": "http://example.com",
  "code": "auth-code",
  "clientSecret": "optional-secret"
}


### Login with Cookie
POST http://localhost:8080/api/login-with-cookie
Content-Type: application/json

{
  "grantType": "authorization_code",
  "clientId": "my-client-id",
  "redirectUrl": "http://example.com",
  "code": "auth-code",
  "clientSecret": "optional-secret"
}


### Login with Header
POST http://localhost:8080/api/login-with-header
Content-Type: application/json

{
  "grantType": "authorization_code",
  "clientId": "my-client-id",
  "redirectUrl": "http://example.com",
  "code": "auth-code",
  "clientSecret": "optional-secret"
}


### Login with Body
POST http://localhost:8080/api/login-with-body
Content-Type: application/json

{
  "grantType": "authorization_code",
  "clientId": "my-client-id",
  "redirectUrl": "http://example.com",
  "code": "auth-code",
  "clientSecret": "optional-secret"
}
